#!/usr/bin/env python3
"""Rewrite the generated parts of README.md from the site's API files.

Reads  : _site/api/index.json, _site/api/latest.json, _site/api/obtainium.json
           (written by tools/gen_site.py, so run that first)
Writes : README.md, only between the markers below

    <!-- apps:start -->            ... one row per app, with download + Obtainium
    <!-- apps:end -->
    <!-- obtainium-links:start --> ... the [obt-*] reference links the badges use
    <!-- obtainium-links:end -->

Every app gets the same treatment - stable or pre-release, today or added later -
so nothing has to be edited by hand when an app or a channel appears.
Stdlib only. Exit 0 whether or not anything changed; prints "changed" or "unchanged".
"""

from __future__ import annotations

import json
import re
import sys
import urllib.parse
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
API = ROOT / "_site" / "api"
README = ROOT / "README.md"

BADGE = "https://img.shields.io/badge/{label}-{message}-{color}?style=for-the-badge&logo=android&logoColor=white"


def _q(text: str) -> str:
    # shields.io: '-' separates fields, so a literal dash is written '--'
    return urllib.parse.quote(text.replace("-", "--"), safe="")


def badge(message: str, color: str) -> str:
    return BADGE.format(label=_q("Add to Obtainium"), message=_q(message), color=color)


def size(n: int) -> str:
    return f"{n / 1e6:.0f} MB" if n else ""


def replace_block(text: str, name: str, body: str) -> str:
    start, end = f"<!-- {name}:start", f"<!-- {name}:end -->"
    pattern = re.compile(rf"{re.escape(start)}.*?{re.escape(end)}", re.S)
    block = f"{start} — generated by tools/gen_readme.py, edits here are overwritten -->\n{body}\n{end}"
    if not pattern.search(text):
        raise SystemExit(f"README.md is missing the {name} markers")
    return pattern.sub(lambda _m: block, text, count=1)


def main() -> int:
    index = json.loads((API / "index.json").read_text(encoding="utf-8"))
    latest = json.loads((API / "latest.json").read_text(encoding="utf-8"))["apps"]
    obt = json.loads((API / "obtainium.json").read_text(encoding="utf-8"))
    entries = {e["app"]: e for e in obt.get("apps", [])}
    conflicts = {c["app"]: c for c in obt.get("conflicts", [])}
    site = index["site"]

    rows = [
        "| App | Channel | Version | Package | Download | Obtainium |",
        "|---|---|---|---|---|---|",
    ]
    for app in index["apps"]:
        build = latest.get(app["id"], {})
        files = build.get("files", [])
        channel = "pre-release" if build.get("prerelease") else "stable"
        download = " · ".join(
            f"[{f['arch']} · {size(f['size'])}]({f['url']})" for f in files
        ) or "—"
        if app["id"] in entries:
            color = "7c3aed" if channel == "pre-release" else "2f6fed"
            obtainium = (
                f"[![Add {app['name']} to Obtainium]({badge(app['name'], color)})][obt-{app['id']}]"
                f"<br>[endpoint]({site}obtainium/{app['id']}.html)"
            )
        elif app["id"] in conflicts:
            c = conflicts[app["id"]]
            obtainium = f"same package as `{c['shares_with']}` — installs over it"
        else:
            obtainium = "—"
        rows.append(
            f"| **{app['name']}** | {channel} | `{app['latest_version']}` | "
            f"`{app.get('package') or '?'}` | {download} | {obtainium} |"
        )

    rows += [
        "",
        f"[![Add every app to Obtainium]({badge('every app', '16a34a')})][obt-all]",
        "",
        f"History of every build: the **All versions** button on the [site]({site}), "
        f"or `api/apps/<app>.json`.",
    ]

    links = [f"[obt-{e['app']}]: {e['add_url']}" for e in obt.get("apps", [])]
    links.append(f"[obt-all]: {obt['add_all_url']}")

    before = README.read_text(encoding="utf-8")
    after = replace_block(before, "apps", "\n".join(rows))
    after = replace_block(after, "obtainium-links", "\n".join(links))

    if after == before:
        print("unchanged")
        return 0
    README.write_text(after, encoding="utf-8")
    print("changed")
    return 0


if __name__ == "__main__":
    sys.exit(main())
