#!/usr/bin/env python3
"""Rewrite the generated parts of README.md from the site's API files.

Reads  : _site/api/index.json, _site/api/latest.json, _site/api/obtainium.json
           (written by tools/gen_site.py, so run that first)
Writes : README.md, only between the markers below

    <!-- apps:start -->            ... a table per channel (stable, pre-release): one row
    <!-- apps:end -->                  per app with its download and Obtainium buttons,
                                       then a folded table of packages, tags, endpoints
    <!-- obtainium-links:start --> ... the [obt-*] reference links the badges use
    <!-- obtainium-links:end -->

Every app gets the same treatment - stable or pre-release, today or added later -
so nothing has to be edited by hand when an app or a channel appears.
Stdlib only. Exit 0 whether or not anything changed; prints "changed" or "unchanged".
"""

from __future__ import annotations

import json
import re
import sys
import urllib.parse
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
API = ROOT / "_site" / "api"
README = ROOT / "README.md"

SHIELD = "https://img.shields.io/badge/{text}-{color}?style=for-the-badge&logo={logo}&logoColor=white"

# Download buttons are coloured by channel; the Obtainium buttons are all one colour
STABLE, PRERELEASE, OBTAINIUM = "16a34a", "7c3aed", "2563eb"


def _q(text: str) -> str:
    # shields.io: '-' separates fields and '_' means a space, so literal ones
    # are doubled
    return urllib.parse.quote(text.replace("-", "--").replace("_", "__"), safe="")


def md(text: str) -> str:
    """Text safe inside a markdown table cell and link label."""
    return re.sub(r"([\\|*_\[\]`])", r"\\\1", str(text))


def shield(label: str, message: str | None, color: str, logo: str) -> str:
    text = _q(label) if message is None else f"{_q(label)}-{_q(message)}"
    return SHIELD.format(text=text, color=color, logo=urllib.parse.quote(logo, safe=""))


def logo_for(name: str) -> str:
    # a Simple Icons slug from the app's first word ("YouTube Experimental" ->
    # "youtube"); shields.io draws no logo for a slug it does not know
    return re.sub(r"[^a-z0-9]", "", name.split()[0].lower()) if name.split() else "android"


def size(n: int) -> str:
    return f"{n / 1e6:.0f} MB" if n else ""


def replace_block(text: str, name: str, body: str) -> str:
    start, end = f"<!-- {name}:start", f"<!-- {name}:end -->"
    pattern = re.compile(rf"{re.escape(start)}.*?{re.escape(end)}", re.S)
    block = f"{start} — generated by tools/gen_readme.py, edits here are overwritten -->\n{body}\n{end}"
    if not pattern.search(text):
        raise SystemExit(f"README.md is missing the {name} markers")
    return pattern.sub(lambda _m: block, text, count=1)


def main() -> int:
    index = json.loads((API / "index.json").read_text(encoding="utf-8"))
    latest = json.loads((API / "latest.json").read_text(encoding="utf-8"))["apps"]
    obt = json.loads((API / "obtainium.json").read_text(encoding="utf-8"))
    catalog_file = API / "catalog.json"
    catalog = json.loads(catalog_file.read_text(encoding="utf-8")) if catalog_file.exists() else {}
    entries = {e["app"]: e for e in obt.get("apps", [])}
    conflicts = {c["app"]: c for c in obt.get("conflicts", [])}
    site = index["site"]

    # One short table per channel: name, version, a download button per APK and
    # an Obtainium button. Packages, tags and endpoints go in a folded table below.
    tables: dict[str, list[str]] = {"stable": [], "pre-release": []}
    details = [
        "| App | Channel | Package | Release | Obtainium endpoint |",
        "|---|---|---|---|---|",
    ]
    links: list[str] = []
    for app in index["apps"]:
        build = latest.get(app["id"], {})
        files = build.get("files", [])
        channel = "pre-release" if build.get("prerelease") else "stable"
        name = md(app["name"])
        logo = logo_for(app["name"])
        color = PRERELEASE if channel == "pre-release" else STABLE
        download = " ".join(
            f"[![Download {name}{'' if f['arch'] == 'all' else ' ' + md(f['arch'])}"
            f"{', ' + size(f['size']) if f['size'] else ''}]"
            f"({shield('Download' if f['arch'] == 'all' else f['arch'], size(f['size']) or None, color, logo)})]"
            f"({f['url']})"
            for f in files
        ) or "—"

        endpoints = []
        if (e := entries.get(app["id"])) is not None:
            label = "Add to Obtainium" if not e.get("variants") else f"Obtainium {e['arch']}"
            badges = [f"[![Add {name} to Obtainium]({shield(label, None, OBTAINIUM, 'obtainium')})][obt-{app['id']}]"]
            links.append(f"[obt-{app['id']}]: {e['add_url']}")
            endpoints.append(f"[{md(e['source_url'].rsplit('/', 1)[-1])}]({e['source_url']})")
            for v in e.get("variants", []):
                ref = f"obt-{app['id']}-{v['arch']}"
                badges.append(
                    f"[![Add {name} {md(v['arch'])} to Obtainium]"
                    f"({shield('Obtainium ' + v['arch'], None, OBTAINIUM, 'obtainium')})][{ref}]"
                )
                links.append(f"[{ref}]: {v['add_url']}")
                endpoints.append(f"[{md(v['source_url'].rsplit('/', 1)[-1])}]({v['source_url']})")
            obtainium = " ".join(badges)
        elif (c := conflicts.get(app["id"])) is not None:
            obtainium = f"same package as {md(c.get('shares_with_name') or c['shares_with'])}, installs over it"
        else:
            obtainium = "not yet (package not read)"

        # Two columns only: the buttons sit side by side on a wide screen and
        # wrap under each other on a phone instead of shrinking
        updated = (app.get("updated") or "")[:10]
        about = f"**{name}**<br>`{app['latest_version']}`" + (f"<br><sub>{updated}</sub>" if updated else "")
        tables[channel].append(f"| {about} | {download} {obtainium} |")

        tag = build.get("tag")
        release = f"[`{tag}`]({build['release_url']})" if tag and build.get("release_url") else "—"
        details.append(
            f"| {name} | {channel} | `{app.get('package') or '?'}` | {release} | "
            f"{' · '.join(endpoints) or '—'} |"
        )

    blurbs = {
        "stable": ("Stable", "The everyday builds. Start here."),
        "pre-release": ("Pre-release", ("Newer app versions with development patches. Each one installs "
                                        "**next to** its stable app, under its own name.")),
    }
    rows: list[str] = []
    for channel, (title, blurb) in blurbs.items():
        if tables[channel]:
            rows += [
                f"### {title}", "", blurb, "",
                "| App | Download or auto-update |",
                "|---|---|",
                *tables[channel], "",
            ]
    if not rows:
        rows = ["No builds yet. The first ones appear here after the next CI run.", ""]

    sources = catalog.get("sources") or {}
    rows += [
        (
            (f"[![Add every app to Obtainium]({shield('Add every app to Obtainium', None, OBTAINIUM, 'obtainium')})]"
             "[obt:all] " if entries else "")
            + f"[![Older versions]({shield('Older versions', None, '475569', 'github')})]({site})"
        ),
        "",
        "<details>",
        "<summary><b>Package names, releases and Obtainium endpoints</b></summary>",
        "",
        *details,
        "",
        f"Every earlier build: the **All versions** button on the [website]({site}), or `api/apps/<app>.json`.",
    ]
    if sources:
        rows += [
            "",
            (
                f"Patch catalog: {len(sources)} sources able to patch {len(catalog.get('packages') or {})} apps, "
                f"in the website's **Catalog** tab or [`data/catalog.json`](data/catalog.json)."
            ),
        ]
    rows += ["", "</details>"]
    links.append(f"[obt:all]: {obt['add_all_url']}")

    before = README.read_text(encoding="utf-8")
    after = replace_block(before, "apps", "\n".join(rows))
    after = replace_block(after, "obtainium-links", "\n".join(links))

    if after == before:
        print("unchanged")
        return 0
    README.write_text(after, encoding="utf-8")
    print("changed")
    return 0


if __name__ == "__main__":
    sys.exit(main())
