#!/usr/bin/env python3
"""Rewrite the generated parts of README.md from the site's API files.

Reads  : _site/api/index.json, _site/api/latest.json, _site/api/obtainium.json
           (written by tools/gen_site.py, so run that first)
Writes : README.md, only between the markers below

    <!-- apps:start -->            ... one row per app, with download + Obtainium
    <!-- apps:end -->
    <!-- obtainium-links:start --> ... the [obt-*] reference links the badges use
    <!-- obtainium-links:end -->

Every app gets the same treatment - stable or pre-release, today or added later -
so nothing has to be edited by hand when an app or a channel appears.
Stdlib only. Exit 0 whether or not anything changed; prints "changed" or "unchanged".
"""

from __future__ import annotations

import json
import re
import sys
import urllib.parse
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
API = ROOT / "_site" / "api"
README = ROOT / "README.md"

BADGE = "https://img.shields.io/badge/{label}-{message}-{color}?style=for-the-badge&logo=android&logoColor=white"


def _q(text: str) -> str:
    # shields.io: '-' separates fields and '_' means a space, so literal ones
    # are doubled
    return urllib.parse.quote(text.replace("-", "--").replace("_", "__"), safe="")


def md(text: str) -> str:
    """Text safe inside a markdown table cell and link label."""
    return re.sub(r"([\\|*_\[\]`])", r"\\\1", str(text))


def badge(message: str, color: str) -> str:
    return BADGE.format(label=_q("Add to Obtainium"), message=_q(message), color=color)


def size(n: int) -> str:
    return f"{n / 1e6:.0f} MB" if n else ""


def replace_block(text: str, name: str, body: str) -> str:
    start, end = f"<!-- {name}:start", f"<!-- {name}:end -->"
    pattern = re.compile(rf"{re.escape(start)}.*?{re.escape(end)}", re.S)
    block = f"{start} — generated by tools/gen_readme.py, edits here are overwritten -->\n{body}\n{end}"
    if not pattern.search(text):
        raise SystemExit(f"README.md is missing the {name} markers")
    return pattern.sub(lambda _m: block, text, count=1)


def main() -> int:
    index = json.loads((API / "index.json").read_text(encoding="utf-8"))
    latest = json.loads((API / "latest.json").read_text(encoding="utf-8"))["apps"]
    obt = json.loads((API / "obtainium.json").read_text(encoding="utf-8"))
    catalog_file = API / "catalog.json"
    catalog = json.loads(catalog_file.read_text(encoding="utf-8")) if catalog_file.exists() else {}
    entries = {e["app"]: e for e in obt.get("apps", [])}
    conflicts = {c["app"]: c for c in obt.get("conflicts", [])}
    site = index["site"]

    rows = [
        "| App | Channel | Version | Package | Download | Obtainium |",
        "|---|---|---|---|---|---|",
    ]
    links: list[str] = []
    for app in index["apps"]:
        build = latest.get(app["id"], {})
        files = build.get("files", [])
        channel = "pre-release" if build.get("prerelease") else "stable"
        name = md(app["name"])
        download = " · ".join(
            f"[{md(f['arch'])} · {size(f['size'])}]({f['url']})" for f in files
        ) or "—"
        if (e := entries.get(app["id"])) is not None:
            color = "7c3aed" if channel == "pre-release" else "2f6fed"
            badges = [f"[![Add {name} to Obtainium]({badge(app['name'], color)})][obt-{app['id']}]"]
            links.append(f"[obt-{app['id']}]: {e['add_url']}")
            for v in e.get("variants", []):
                label = f"obt-{app['id']}-{v['arch']}"
                badges.append(f"[![{name} {md(v['arch'])}]({badge(app['name'] + ' ' + v['arch'], color)})][{label}]")
                links.append(f"[{label}]: {v['add_url']}")
            obtainium = "<br>".join(badges) + f"<br>[endpoint]({site}obtainium/{app['id']}.html)"
        elif (c := conflicts.get(app["id"])) is not None:
            obtainium = f"same package as {md(c.get('shares_with_name') or c['shares_with'])} — installs over it"
        else:
            obtainium = "— (package not read yet)"
        rows.append(
            f"| **{name}** | {channel} | `{app['latest_version']}` | "
            f"`{app.get('package') or '?'}` | {download} | {obtainium} |"
        )

    sources = catalog.get("sources") or {}
    rows += [
        "",
        f"[![Add every app to Obtainium]({badge('every app', '16a34a')})][obt:all]",
        "",
        f"History of every build: the **All versions** button on the [site]({site}), "
        f"or `api/apps/<app>.json`.",
    ]
    if sources:
        rows.append(
            f"Patch catalog: {len(sources)} sources able to patch {len(catalog.get('packages') or {})} apps — "
            f"the **Catalog** tab, or [`data/catalog.json`](data/catalog.json)."
        )
    links.append(f"[obt:all]: {obt['add_all_url']}")

    before = README.read_text(encoding="utf-8")
    after = replace_block(before, "apps", "\n".join(rows))
    after = replace_block(after, "obtainium-links", "\n".join(links))

    if after == before:
        print("unchanged")
        return 0
    README.write_text(after, encoding="utf-8")
    print("changed")
    return 0


if __name__ == "__main__":
    sys.exit(main())
